### ISSUE TITLE
To-do list

### ISSUE THREAD

**Issue by DidDrog11** [DidDrog11/phd_project#1]
- [x] Update abstract
- [x] Sort appendices/supplementary material
- [x] List of Acronyms
- [x] Acknowledgements
- [x] Thesis outputs
- [x] Fix tables not working with kable, maybe try GT?
- [x] Fix images floating beyond sections
- [x] Change from PhD outputs and additional outputs to thesis outpus
- [x] Keep prefaces but add in the outputs as part of them
- [x] Add methods chapter for rodent trapping
- [x] Add et al. to Figure 5.1 references
- [x] Bibliography change citation to include all author names
- [x] Bibliography hanging indent in between references

# Richards comments
- [x] Abstract
  - [x] Change from endemic zoonotic infectious diseases to endemic zoonoses
- [ ] Introduction
  - [x] Duplicated from section 1.1
  - [x] Bird flu change to "leads to significant morbidity and mortality in some infected bird species (i.e., galliform), alongside pathogenicity in humans during rare zoonotic spillover events."
  - [x] Add sentence after mentioning Nipah and Lassa. "However, Nipah virus infection differs importantly from LASV with most human outbreaks associated with direct infection from an amplifying intermediate host, rather than direct infection from the reservoir species." 
  - [x] Pathogens better adapted to transmission among humans (e.g., HIV and SARS-CoV-2), remove the e.g., from the following sentence.
  - [x] Change "may become" to be "may be described as"
  - [x] "spillback" i.e., reverse zoonosis or zoonathroponosis
  - [x] Change "and alternatively", to 'further"
  - [x] Change example of initial spillover event to MERS outbreaks instead of SARS-CoV-2
  - [x] Change "LASV highlights the risk of recurrent local spillover into human populations in endemic regions" to "LASV highlights the risk of endemic zoonoses leading to recurrent local spillover events into human populations in endemic regions"
  - [x] Change from "This framework is particularly useful when considering how spillover of zoonoses occur" to "This framework is particularly useful when considering changes in risk from zoonoses occurring in the context of "
  - [x] "Anthropogenic climate change has long been known to modify the risk of spillover of zoonoses" to "Anthropogenic climate change has long been known to modify the risk of zoonoses to human populations through"
  - [x] Add to "specific disease context" "specific disease context, with limited generalisability between disease systems."
  - [x] After mentioning 60% of emerging human infectious diseases are known zoonosis, state that only a minority of these fulfil the WHO definition of a zoonoses, check Richards IUCN report for references
  - [x] When discussing the diversity of zoonoses add in a section on the small proportion of them that lead to the most cases, i.e., not all of these are important from a public health perspective
  - [x] Section 1.6.1, "It is a zoonotic pathogen and an established zoonosis, causing Lassa fever in humans." 
  - [x] Longest reported chain of transmission for LF?
  - [x] Add reservoir host after first mention of primary host
  - [x] At end of human pathogenicity section add "There is no understanding currently on the association of route of infection with disease severity or pathogenicity in humans."
  - [x] After discussing CFR, "Currently there is no data supporting estimation of the infection-fatality rate for Lassa fever as the intensive surveillance and monitoring required for this has not been performed in the endemic region."
  - [x] How long until humans clear viral RNA?
  - [ ] How many observed events of secondary human-to-human transmission outside of the endemic region?
  - [x] Figure 1.4, change from red border to dashed border
  - [x] Figure 1.5, add data to appendix
  - [x] 1.6.3 "While M. natalensis is currently considered the only reservoir of LASV"
  - [x] Why does the presence of other Arenaviridae limit the range of LF?
  - [x] Species in parenthesis when describing LASV prevalence in Guinea, Mali and SL
  - [x] Change not shown in Figure 1.6 to "absence of acute infection not shown in Figure 1.6)
  - [x] "prediting" to "predicting"
  - [x] 1.7 "future risk of Lassa fever spillover" to "future risk of Lassa fever spillover and zoonosis in West"
  - [x] "This thesis aimed to address some of the critical gaps in understanding of LASV transmission among rodent communities in endemic settings, whether there is a need to mover away from the single reservoir species paradigm and the effect of "
- [x] Chapter 3 
  - [x] zoonotic infectious disease to zoonosis
- [x] Chapter 4
  - [x] zoonotic infectious disease to zoonosis
  - [x] Table 4.1 add "by species" to legend
- [ ] Conclusions
  - [x] Importance of improving diagnostics and underreporting of disease? 
  - [x] Is single infection with antibody response leading to life long iimmunity? 
  - [x] Infection in rodent predators - domestic and wild? 
  - [x] "invived" to "involved"

# Debby's comments

Majority listed as tracked changes in word document

- [ ] Methods chapter
  - [ ] Add images of traps, and in locations
  - [x] Other changes made directly based on word document

# Kate's comments

Majority listed as tracked changes in word document

- [ ] Methods chapter
  - [x] Add maps of trap locations
  - [x] Reference sampling protocols
  - [x] Add figure to demonstrate trap grids
